command:
  - streamlit
  - run
  - lm_cost_app.py
  - --server.port
  - $DATABRICKS_APP_PORT
  - --server.address
  - 0.0.0.0
  - --server.headless
  - "true"

env:
  - name: NORM_DATA_PATH
    value: "/Workspace/Users/sgt4gul@mckessoncorp.onmicrosoft.com/Last Mile/LastMile/apps/lm_cost/data/LM_CS_slim.csv.gz"
